# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."llamacpp" = {
    image = "ghcr.io/ggml-org/llama.cpp:server-vulkan";
    environment = {
      "LLAMA_ARG_MODELS_DIR" = "/models";
      "LLAMA_ARG_MODELS_PRESET" = "/models/presets.ini";
      "LLAMA_ARG_PORT" = "8080";
    };
    volumes = [
      "/home/matty/.config/llamacpp/models:/models:rw"
    ];
    ports = [
      "8080:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=/dev/dri:/dev/dri:rwm"
      "--network-alias=llamacpp"
      "--network=llamacpp_default"
    ];
  };
  systemd.services."docker-llamacpp" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-llamacpp_default.service"
    ];
    requires = [
      "docker-network-llamacpp_default.service"
    ];
    partOf = [
      "docker-compose-llamacpp-root.target"
    ];
    wantedBy = [
      "docker-compose-llamacpp-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-llamacpp_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f llamacpp_default";
    };
    script = ''
      docker network inspect llamacpp_default || docker network create llamacpp_default
    '';
    partOf = [ "docker-compose-llamacpp-root.target" ];
    wantedBy = [ "docker-compose-llamacpp-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-llamacpp-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
