# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd.availableKernelModules = [
      "xhci_pci"
      "ahci"
      "nvme"
      "usb_storage"
      "usbhid"
      "sd_mod"
    ];

    initrd.kernelModules = [
      "vfio_pci"
      "vfio"
      "vfio_iommu_type1"

#       "nvidiafb"
#       "nouveau"
#       "nvidia_drm"
#       "nvidia"
    ];

    kernelParams = [
      "intel_iommu=on"
      "vfio-pci.ids=10de:1f08,10de:10f9,10de:1ada,10de:1adb"
    ];
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];

    blacklistedKernelModules = [
      "nouveau"
      "nvidia"
      "nvidiafb"
      "nvidia-drm"
      "nvidia-uvm"
      "nvidia-modeset"
    ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/28dd4416-ef41-4fa1-81a2-d0dc27ec620b";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6BB5-2B72";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

	swapDevices = [ ];

	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    nixpkgs.config.rocmSupport = true;
#     nixpkgs.config.cudaSupport = true;

	hardware = {
      cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
      bluetooth.enable = true;

      graphics = {
        enable = true;
        enable32Bit = true;
      };

      amdgpu = {
        opencl.enable = true;
        initrd.enable = true; # sets boot.initrd.kernelModules = ["amdgpu"];
        overdrive.enable = true;
      };

      nvidia = {
        open = false;
      };
	};
}
